version: '3'
services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - '9000:9000'
      - '4000:4000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  webhook:
    container_name: webhook
    restart: always
    image: nginx
    volumes:
      - '$PWD/../Webhook-receiver/dist:/usr/share/nginx/html:ro'
    ports:
      - '80:80'
    links:
      - api:4000
