version: '3'
services:
  app:
    container_name: api
    restart: always
    build: .
    ports:
      - '9000:9000'
      - '4000:4000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
